language : node_js
node_js :
 - 10
install:
 - npm install yarn -g
 - yarn install
script:
  - docker build -t $DOCKER_USER/blog-koa .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_USER/blog-koa