language : node_js
node_js :
 - 10
install:
 - yarn install
script:
  - docker build -t $DOCKER_USER/blog-koa:latest .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_USER/blog-koa:latest
  - docker tag $DOCKER_USER/blog-koa:latest $DOCKER_USER/blog-koa:$VERSION
  - docker push $DOCKER_USER/blog-koa:$VERSION